### ISSUE TITLE
(Resolved) Predator Bear modifier bug

### ISSUE THREAD

**Issue by digydigdogdead** [WildgrassGames/BEARZERKERS#2]
Unfortunately the bear is not always invisible when far away which gives away its location.
When the bear enters a rage mode, you can see its glowing eyes and mouth.
and when the bear enters and oil spill you can see the trail it leaves behind.

Love the game guys.

**Comment by WildgrassGames** [comment]
https://trello.com/c/Sjown1um/1292-bear-rage-effects-still-appear-while-bear-is-hidden-with-predator-bear-modifier
